### ISSUE TITLE
Switch to Anaconda

### ISSUE THREAD

**Issue by nathan-osman** [AskUbuntu/tbot#2]
The `go-twitter` package is nice but it appears to lack support for image uploads. `anaconda` is a more popular Twitter client package and switching to it should be relatively simple (I hope).
### What This Involves

This one is relatively simple. All of the code for interfacing with the Twitter API is located in `twitter/twitter.go`.

**Comment by Psidium** [comment]
Hey, can I do this?

**Comment by nathan-osman** [comment]
Sure! Let me know if you have any questions.
