### ISSUE TITLE
Logo is needed

### ISSUE THREAD

**Issue by nathan-osman** [AskUbuntu/tbot#4]
The app does not have a favicon nor a logo.

**Comment by jojo1311** [comment]
Hi, @nathan-osman I can help with the logo and favicon.  For the logo I will need more info.  Is there a way we can talk or chat (i.e email, slack, google chat etc...)

**Comment by nathan-osman** [comment]
Feel free to contact me via Hangouts (Google Talk) using `nathan.osman@gmail.com`.

**Comment by jojo1311** [comment]
I'll be creating some sketches and will send it to you tomorrow, so we can either chat or email based on that.

**Comment by nathan-osman** [comment]
Closed by #8
